name: ej1-workflow

on: 
  push:
    branches:
      - main

jobs: 
  tareas:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar codigo
        uses: actions/checkout@v4
      - name: Configurar entorno Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Ejecutar comando
        run: npm i
      - name: Ejecutar tests
        run: npm test
      - name: Construir imagen
        uses: cloudposse/github-action-docker-compose-test-run@main
        with:
            file: ./docker-compose.yml
            service: app
          
